### ISSUE TITLE
[QUESTION] Automate already existent files in cloud storage.

### ISSUE THREAD

**Issue by CyberPoison** [zzeneg/docker-mergesrt#3]
Hello @zzeneg 

I have a question regarding your app/script, do you get any feedback for those using Cloud Storage (i.e:. Gdrive,Dropbox,etc) i'm in need to merge srt (Around 3K files) from a cloud based storage, and i need to know if this can scan+ merge the srt to the mp4/mkv files, without transcode "changes in terms on quality" or at least with a copy:copy ffmpeg command. 

Could you bring some lights to my question ?

**Comment by zzeneg** [comment]
Hey, as long as your files are synced to a linux system, I don't see why it would not work. And yes, this script copies streams without any transcoding.
